# Урок 2

## Матрицы и матричные операции. Часть 1

## Практическое задание

Все задания рекомендуется делать вручную, затем проверяя полученные результаты с использованием numpy.

__1.__ Установить, какие произведения матриц $AB$ и $BA$ определены, и найти размерности полученных матриц:

   а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$;
    
   б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$;
    
   в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$;
    
   г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$.
   
   Так как произведением матрицы  𝐴=‖‖𝑎𝑖𝑗‖‖ , имеющей порядки  𝑚  и  𝑛 , и матрицы  𝐵=‖‖𝑏𝑖𝑗‖‖ , имеющей порядки  𝑛  и  𝑘 , называется матрица  𝐶=‖‖𝑐𝑖𝑗‖‖ , имеющая порядки  𝑚  и  𝑘 , то делаем выводы
   
   а) поизведения матриц $AB$ и $BA$ не определены т.к. количество столбцов не равно количеству строк, $4 <> 2$, $2<>4$;
   б) поизведения матрицы $BA$ не определено -//-, поизведения матрицы $AB$ - определено и размерность будет $2\times 3$;
   в) поизведения матриц $AB$ и $BA$ определены т.к. количество столбцов равно количеству строк, для  $AB$ 3=3 и размерность => $8\times8$ , для  $BA$ 8=8 и размерность => $3\times3$;
   г) У квадратных матриц в случае если их размерность одинаковая, произведение будет в обоих случаях, размерность новых матриц будет такая же как размерность матриц $A$, $B$ $4\times 4$, $B$

In [16]:
#a)
import numpy as np
a = np.array([[1,2,3,4],[1,2,3,4]])
b = np.array([[1,2,3,4],[1,2,3,4]])
ab = np.dot(a,b)
print(ab)

ValueError: shapes (2,4) and (2,4) not aligned: 4 (dim 1) != 2 (dim 0)

In [17]:
ba = np.dot(b,a)
print(ba)

ValueError: shapes (2,4) and (2,4) not aligned: 4 (dim 1) != 2 (dim 0)

In [18]:
#б)
a = np.array([[1,2,3,4,5],[1,2,3,4,5]])
b = np.array([[1,2,3],[1,2,3],[1,2,3],[1,2,3],[1,2,3]])
ab = np.dot(a,b)
print(ab)

[[15 30 45]
 [15 30 45]]


In [15]:
ba = np.dot(b,a)
print(ba)

ValueError: shapes (5,3) and (2,5) not aligned: 3 (dim 1) != 2 (dim 0)

In [23]:
#в)
a = np.array([[1,2,3],[1,2,3],[1,2,3],[1,2,3],[1,2,3],[1,2,3],[1,2,3],[1,2,3]])
b = np.array([[1,2,3,4,5,6,7,8],[1,2,3,4,5,6,7,8],[1,2,3,4,5,6,7,8]])
ab = np.dot(a,b)
ba = np.dot(b,a)
print(ab)
print(ba)

[[ 6 12 18 24 30 36 42 48]
 [ 6 12 18 24 30 36 42 48]
 [ 6 12 18 24 30 36 42 48]
 [ 6 12 18 24 30 36 42 48]
 [ 6 12 18 24 30 36 42 48]
 [ 6 12 18 24 30 36 42 48]
 [ 6 12 18 24 30 36 42 48]
 [ 6 12 18 24 30 36 42 48]]
[[ 36  72 108]
 [ 36  72 108]
 [ 36  72 108]]


In [26]:
#г)
a = np.array([[1,2,3,4],[1,2,3,4],[1,2,3,4],[1,2,3,4]])
b = np.array([[1,2,3,4],[1,2,3,4],[1,2,3,4],[1,2,3,4]])
ab = np.dot(a,b)
ba = np.dot(b,a)
print(ab)
print(" ")
print(ba)

[[10 20 30 40]
 [10 20 30 40]
 [10 20 30 40]
 [10 20 30 40]]
 
[[10 20 30 40]
 [10 20 30 40]
 [10 20 30 40]
 [10 20 30 40]]


   
__2.__ Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$

у матриц есть свойство коммутативности,  тоесть $A+B=B+A$ достаточно тнайти сумму одного сочетания и 2x матриц $AB$ и $BA$:

 $A+B = \begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$+$\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}$ = $\begin{pmatrix}
5 & -3\\ 
3 & 5
\end{pmatrix}$

 $A\times B = \begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ $\times$ $\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}$ = $\begin{pmatrix}
4 & -11\\ 
12 & -3
\end{pmatrix}$

 $B\times A = \begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}$ $\times$ $\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ = $\begin{pmatrix}
4-3 & -8+0\\ 
15 & 0
\end{pmatrix}$= $\begin{pmatrix}
1 & -8\\ 
15 & 0
\end{pmatrix}$

In [27]:
a = np.array([[1,-2],[3,0]])
b = np.array([[4,-1],[0,5]])
ab = np.dot(a,b)
ba = np.dot(b,a)
print(a + b)
print(" ")
print(ab)
print(" ")
print(ba)

[[ 5 -3]
 [ 3  5]]
 
[[  4 -11]
 [ 12  -3]]
 
[[ 1 -8]
 [15  0]]



__3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$

$3A-2B+4C$ =$\begin{pmatrix}
3-0+8 & 21-10-16\\ 
9-4+4 & -18+2+4
\end{pmatrix}$ =$\begin{pmatrix}
11 & -5\\ 
9 & -12
\end{pmatrix}$

In [29]:
a = np.array([[1,7],[3,-6]])
b = np.array([[0,5],[2,-1]])
c = np.array([[2,-4],[1,1]])
abc = 3*a-2*b+4*c
print(abc)

[[ 11  -5]
 [  9 -12]]


__4.__ Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$.


In [37]:
a = np.array([[4,1],[5,-2],[2,3]])
aT = a.transpose()
aaT = np.dot(a,aT)
print(aaT)
print(" ")
aTa = np.dot(aT,a)
print(aTa)

[[17 18 11]
 [18 29  4]
 [11  4 13]]
 
[[45  0]
 [ 0 14]]


__5*.__ Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

# Матрицы и матричные операции. Часть 2

## Практическое задание

Все задания рекомендуется выполнять вручную, затем проверяя полученные результаты с использованием Numpy.

__1.__ Вычислить определитель:

   a)

$$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix};$$

$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix}$ = $sinx^2 \times cosx^2$ = 1


   б)
    
$$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix};$$

$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix}$ = $4 \times(45-0)-2\times(0-0) +3\times(0-0) = 180$
    
   в)

$$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix}$$



$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix}$ = $1 \times(45-48)-2\times(36-42) +3\times(32-35) = 0$

In [38]:
a = np.array([[4,2,3],[0,5,1],[0,0,9]])
np.linalg.det(a)

180.0

In [41]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
round(np.linalg.det(a),1)

0.0


__2.__ Определитель матрицы $A$ равен $4$. Найти:

   а) $det(A^{2})$;
    
   б) $det(A^{T})$;
    
   в) $det(2A)$.

 __3.__  Доказать, что матрица

$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$
вырожденная.

Матрица называется сингулярной, или вырожденной, если ее определитель равен нулю. Если в ходе преобразований, к одной из строк матрицы прибавить другую, умноженную на число, ее определитель не изменится такой определитель можно будет представить в виде суммы двух, первый из которых будет равен исходному, а второй будет содержать линейно зависимые строки, в связи с чем обратится в ноль.

если первую строчку умножить на -2 то она станет равной второй строке, а значит она вырожденная. 

In [42]:
a = np.array([[-2,7,-3],[4,-14,6],[-3,7,13]])
np.linalg.det(a)

0.0

__4.__ Найти ранг матрицы:

   а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix};$

   б) $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$

In [44]:
a = np.array([[1,2,3],[1,1,1],[2,3,4]])
np.linalg.matrix_rank(a)

2

In [45]:
b = np.array([[0,0,2,1],[0,0,2,2],[0,0,4,3],[2,3,5,6]])
np.linalg.matrix_rank(b)

3